# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
<<<<<<< Updated upstream
    branches:
      - Develop
  pull_request:
    branches:
      - Develop
=======
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
>>>>>>> Stashed changes

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
<<<<<<< Updated upstream
          distribution: 'adopt'
          java-version: '11'

      - name: Create Application YAML
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.BOOGIE_SECRET }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: LeeHusung # 계정 명
          REPO: boogie # 레포 이름
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
#
#      # --------------------------추가
#      - name: Make Zip File
#        run: zip -qq -r ./$GITHUB_SHA.zip .
#        shell: bash
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Upload to S3
#        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
#
#      - name: Code Deploy To EC2 instance
#        run: aws deploy create-deployment
#          --application-name $CODE_DEPLOY_APP_NAME
#          --deployment-config-name CodeDeployDefault.AllAtOnce
#          --deployment-group-name $DEPLOYMENT_GROUP_NAME
#          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
## --------------------------추가
=======
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICAITION_YML }}" > ./src/main/resources/application.properties
      # - run: cat ./src/main/resources/application.properties
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar
>>>>>>> Stashed changes
