name: CI/CD

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

env:
  PROJECT_NAME: boogie
  BUCKET_NAME: boogie-cicd-bucket
  CODE_DEPLOY_APP_NAME: boogie_cicd
  DEPLOYMENT_GROUP_NAME: boogie_instance

jobs:
  build:
    runs-on: amazon-linux-2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create Application YAML
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.BOOGIE_SECRET }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Zip File
        run: zip -qq -r ./boogie-app.zip build/libs/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./boogie-app.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA/boogie-app.zip

      - name: Code Deploy To EC2 instance
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA/boogie-app.zip
